apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: consumer
  labels:
    type: consumer-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        type: consumer-infra
    spec:
      containers:
        - name: postgres
          image: postgres:17.7-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "controlplane"
            - name: POSTGRES_USER
              value: "cp"
            - name: POSTGRES_PASSWORD
              value: "cp"
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: postgres-init

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: consumer
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: consumer
data:
  init.sql: |
    -- The default database "controlplane" and user "cp" are created by:
    -- POSTGRES_DB=controlplane
    -- POSTGRES_USER=cp
    -- POSTGRES_PASSWORD=cp

    -- IdentityHub database
    CREATE USER ih WITH PASSWORD 'ih';
    CREATE DATABASE identityhub OWNER ih;
    GRANT ALL PRIVILEGES ON DATABASE identityhub TO ih;

    \c identityhub
    GRANT ALL ON SCHEMA public TO ih;

    -- Dataplane database
    \c postgres
    CREATE USER dp WITH PASSWORD 'dp';
    CREATE DATABASE dataplane OWNER dp;
    GRANT ALL PRIVILEGES ON DATABASE dataplane TO dp;

    \c dataplane
    GRANT ALL ON SCHEMA public TO dp;